PygmentsCodeFences = false
baseURL = "/"
copyright = "CC BY 4.0"
defaultContentLanguage = "en"
enableEmoji = true
footnoteReturnLinkContents = "↩"
googleAnalytics = ""
hasCJKLanguage = true
languageCode = "en-gb"
paginate = 7
theme = "pure"
title = "Sysadmin Explained"
[[menu.main]]
identifier = "tags"
name = "Tags"
title = "Tags"
url = "/tags/"
weight = 4
[[menu.main]]
identifier = "categories"
name = "Categories"
title = "Categories"
url = "/categories/"
weight = 3
[[menu.main]]
identifier = "archives"
name = "Archives"
title = "Archives"
url = "/posts/"
weight = 2
[[menu.main]]
identifier = "home"
name = "Home"
title = "Home"
url = "/"
weight = 1
[outputFormats.SearchIndex]
baseName = "searchindex"
isPlainText = true
mediaType = "application/json"
notAlternative = true
[outputs]
home = ["HTML", "RSS", "SearchIndex"]
[params]
copyright_link = "http://creativecommons.org/licenses/by/4.0"
dateFormatToUse = "2006-01-02"
enableMathJax = true
enablePostCopyright = true
mainSections = ["posts"]
sidebar = "right"
since = 2017
widgets = ["board", "tag_cloud", "category", "tag", "recent_posts"]
[params.comment]
disqus = "your_disqus_name"
[params.comment.gitalk]
[params.comment.valine]
avatar = "mm"
meta = "nick,mail"
pageSize = 10
placeholder = "enjoy~"
visitor = false
[params.config]
excerpt_link = "Read More"
layout = "main-center"
skin = "theme-black"
toc = true
[params.donate]
enable = false
[params.highlightjs]
langs = ["python", "javascript"]
[params.menuIcons]
about = "icon-cup-fill"
archives = "icon-archives-fill"
books = "icon-book-fill"
categories = "icon-folder"
enable = true
home = "icon-home-fill"
links = "icon-friendship"
repository = "icon-project"
tags = "icon-tags"
[params.postCount]
enable = true
min2read = true
wordcount = true
[params.profile]
author = "Adam"
author_description = "The more you break, the more you learn to fix."
author_title = "IT Guy"
avatar = "images/avatar.png"
enabled = true
follow = "https://github.com/adamprice56"
location = "Manchester, UK"
[params.profile.social]
link_tooltip = false
[params.profile.social.links]
github = "https://github.com/adamprice56"
rss = "/index.xml"
[params.pv.busuanzi]
enable = false
[params.pv.leancloud]
enable = false
[params.search]
enable = true
[params.share]
enable = true
mobile_sites = "weibo,qq,qzone"
sites = "weibo,qq,wechat,facebook,twitter"
[params.site]
board = "<p>enjoy</p>"
favicon = "images/favicon.ico"
title = "Hugo"
[params.site.logo]
enabled = true
height = 40
url = "images/favicon.ico"
width = 40
[params.tag_cloud]
max = 20
min = 8
[permalinks]
posts = "/:year/:month/:filename/"
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
[taxonomies]
category = "categories"
series = "series"
tag = "tags"
